### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Dylan-DPC**

### CODE REVIEW

**Comment by danhunsaker** [comment]
This doesn't seem to actually change anything, except to prevent an eventual 5.6 release from being supported without changing the `composer.json` again. `^5.0` means `5.0 or higher, but less than 6.*, in accordance with SemVer`.

**Comment by Dylan-DPC** [comment]
Exactly. But Laravel doesn't follow semver. So a breaking change in 5.6 can break your package. The difference is with the original versioning you had, composer will still install it and then user will find out it is not supported. With this change, composer will refuse to install it

**Comment by danhunsaker** [comment]
Fair enough, but that's a thing to handle once there actually _is_ a breaking change.

**Comment by freekmurze** [comment]
Even though you're right in theory, I'm not going to pull it in. This package uses very common functionality from Laravel that has a low chance of getting breaking changes.

**Pull request closed without merging**
