### PR TITLE
Support for reverse geocoding

### PR DESCRIPTION
**Pull request by pascalbaljet**

### CODE REVIEW

**Comment by danhunsaker** [comment]
For future reference, closing #26 and opening this one wasn't necessary, as GitHub treats the _branch_ as the requested merge source, not the _commit_, so #26 and #27 are identical PRs.

**Comment by pascalbaljet** [comment]
I know but it's Travis' recommended way of triggering a new build. I'm getting some inconsistent responses from the Google API. The Travis build failed after I changed the documentation 🤔

Before: https://travis-ci.org/spatie/geocoder/builds/292569694?utm_source=github_status&utm_medium=notification
After: https://travis-ci.org/spatie/geocoder/builds/292600078?utm_source=github_status&utm_medium=notification

**Comment by danhunsaker** [comment]
Travis ... needs to come up with better options, because that's a good way to pollute a project's issues list with duplicates... I'd probably set up my own fork to run tests on push, so I can trigger tests manually myself, there, until things are working properly.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
