### PR TITLE
Added params

### PR DESCRIPTION
**Pull request by michelecurletta**
Added params

### CODE REVIEW

**Comment by freekmurze** [comment]
Will take a look after travis runs properly again, don't worry too much about the styling issues.

**Comment by freekmurze** [comment]
Some things that need be taken care of before I can pull this:
- The tests seem to fail on Travis. Can you fix this?
- Could you also add some extra tests in the test suite to make sure your extra parameters work? 
- Could you update the readme?

**Comment by shockgonewild** [comment]
The problem in this PR is the use of Laravel helpers ( in this case config() ) . Is this package supposed to work for laravel only, or is the intention to NOT couple it tightly to the laraevl framework ?

**Comment by freekmurze** [comment]
This package is framework agnostic.

**Comment by shockgonewild** [comment]
Then honestly I think, you should move this package from the laravel section to your php section on your homepage. Declaring it as Laravel specific leads to PRs like this ( which is valid code in Laravel environment )

**Comment by freekmurze** [comment]
Try that. Done! (it was on the Laravel page by mistake)

**Comment by michelecurletta** [comment]
@freekmurze sorry but in the past days I was busy in other stuff: I'll finish this PR.
Considering that this package is not laravel specific, maybe the config file is not the appropriate place to put params configurations (because config files are laravel's specific stuff); @freekmurze that do you think about?

**Comment by freekmurze** [comment]
No problem, take your time.

Maybe just use some fluent setters to pass in the config data?

**Comment by michelecurletta** [comment]
@freekmurze now I think it is ok.
The package is framework agnostic, but works properly also with Laravel conventions (like config files). What is your opinion?

**Comment by shockgonewild** [comment]
I personally don't like that approach.  What if a function called config() already exists, but the user is not using Laravel Framework?

**Comment by michelecurletta** [comment]
@shockgonewild any suggestions?

**Comment by shockgonewild** [comment]
I think it would be best, to set the options in constructor ( or fluent set methods). If used with Laravel you can bind it to the Service Container with parameters.

**Comment by michelecurletta** [comment]
@shockgonewild ok, I agree with you

**Comment by shockgonewild** [comment]
Pretty Cool Now ;)  This should get mergedn, as soon as you update the docs ( For Laravel installation and also for standalone )

**Comment by michelecurletta** [comment]
@shockgonewild done.
@freekmurze is it ok for you?

**Comment by michelecurletta** [comment]
the end :)

**Comment by freekmurze** [comment]
Thank you, I'll clean this up a bit and tag a new version.

**Pull request merged**
